Australia: ANZ,AWC,BXB,CBA,CPU,CWN,FMG,GMG,GPT,ILU,IPL,LLC,MQG,NAB,NCM,OSH,QAN,QBE,SGP,SHL,STO,SYD,TCL,TLS,WPL
Austria: ERST,EVNV,LNZ,MMKV,OMVV,RBI,SBO,STR,VOES,WBSV,ZAG
Belgium: ACKB,ABI,COFB,COLR,GBLB,KBC,SOLB,UCB,UMI,ONTEX,PROX,SOF,WDP
Brazil: PBRa,CIGC,OIBR_C,EBR_B
Canada: ARX,ABX,BBD_A,BBD_B,BAM_A,CTC_A,GIB_A,ATD_B,WN,HSE,IPL,MRU,NA,POW,RCI_B,SJR_B,SNC,T_A,YRI
Chile: AKO_A,AKO_B
Czech: KOFOL,ERBAG,KOMB,MONET,TELEC,PEGAS,TABAK,TMR,STOCK
Denmark: MAERSKb,CARLb,CHR,COLOb,DANSKE,DSV,GN,ISS,NZYMb,NOVOb,PNDORA,VWS,LUN,ORSTED,AMBUb,RBREW,DEMANT,TRYG
European:ENI,NESN,HSBA,FP,SIE,AIR,BNP,ABI,BAS,DAI,ISP,SAPG,ABBN,BATS,DGE,GLEN,LLOY,NOVOb,ULVR,RB,RDSa,UBSG,ZURN,UNA
France:EN,LR,RI,PUBP,GLE,BNP,CAP,CA,BN,ML,RNO,SGO,FP,KER,AIR,ENGI,EXHO,URW,HRMS,DAST,TCFP
Germany:DBK,BAS,BEI,DAI,DB1Gn,EOAN,FRE,IFX,MRCG,RWE,SAPG,VOW3,BMW,FME,HEN3,MUV2,LHA,SIE,TKA,1COV,VNA,WDI,CONG
Greece:ELPE,ETE
Italy:A2A,ATL,BZU,CPR,ENEL,ENI,ISP,MDBI,PRY,TENR,TLIT,UBI,AZMT,UCG,UNI,GASI,BPE,EXO,MONC,SFER,BAMI,PIRC,JUVE,RECI,DIAS,LDO,HER,NEXI,BGN
Netherlands:KPN,PHIA,WKL,AALB,NN,VOPA,ABN,AD,ASRNL,URW,REN,AKZA,RDSa,ADYEN,IMCD,UNA
Nordic:ASSAB,ATCOa,BOL,CARLb,DANSKE,DSV,ELUXb,ERICb,GETIb,HMb,INVEb,KNEBV,MAERSKb,NOVOb,OUT1V,SEBa,SHBa,SCAb,SKAb,SKFb,SSAB_A,STERV,SWED_A,SWMA,TEL2b,VOLVb,VWS,WRT1V
Norway:DNB,DNO,GJF,NHY,ORK,YAR,NAS,SUBC,BAKKA,LSG,AKERBP,EQNR,BWO,NEL,MOWI,TOM,BWLPG
Peru:FSSLY
Poland:ACP,BHW,BRS,GTC,JSW,KER,KGH,LWB,PGE,PKN,PGN,PZU,SNS,TPE
Portugal:93ALTR,BCP,EDP,EDPR,EGL,GALP,IPR,JMT,NOS,RENE,TDSA,IBS,RAM,SONC
Russia:MNOD,SGGD,VTBR,ATAD,OGZD,NVTK,LKOD,SBER,
Sorthern Europe:ITX,REP,ELE,CABK,GALP,ACS,IBE,EDP,MAP,JMT,FER,REE,SAB,ANA,ZOT,EDPR,ACX,BCP,FCC,PSG,TRE,EBRO,OHL,IDR,ELPE
Spain:ACS,ACX,ANA,CABK,ELE,FER,IBE,IDR,ITX,MAP,MTS,REE,REP,SAB,TL5,TRE,SGRE,ENC,MEL,MRL,CLNX,AENA,BKIA,COL,CIE
Sweden:ELUXB,ERICB,GETIB,HMB,INVEB,SEBA,SECUB,SKAB,SKFB,SSAB_A,SCAB,SWED_A,SWMA,VOLVB,TEL2B,SHBA,ASSAB,TELIA,ALIVSDB,ESSITY_B,ATCOA,ATCOB,BOL,HEXAB,KINV_B
Switzerland:ABBN,ADEN,CSGN,GEBN,LONN,GIVN,NESN,SGSN,UHR,SLHN,SCMN,ZURN,UBSG,SREN,LHN,SIKA
United Kingdom:ANTO,ABF,AV,BARC,BDEV,BKG,BATS,BLND,BT,BNZL,BRBY,CPI,CRH1,DCC,DGE,DLG,DC,EXPN,FRES,GLEN,HMSO,HIK,HSBA,IMB,ITV,SBRY,JMAT,KGF,LGEN,LLOY,LSE,MKS,MNDI,NXT,PSON,RB,REL,RR,RDSA,RDSB,RSA,SGE,SDR,SN,SSE,STJ,STAN,TPK,TUI,ULVR,UU,WEIR,WTB,WPP,SLA,FERG,SKG,NMC,OCDO,GVC,SGRO,RMV,WG,SPX,SMT,SMDS,HSX,HLMA,CRDA,MRWA,RTO
United States: