# Generated by Django 2.2.10 on 2020-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('sure_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('permission', models.IntegerField(default=2)),
                ('status', models.CharField(default='enable', max_length=20)),
                ('expire_date', models.DateField()),
                ('ib_id', models.IntegerField()),
                ('ib_port', models.IntegerField()),
                ('saxo_token', models.TextField()),
            ],
        ),
    ]
