# Generated by Django 2.2.10 on 2020-02-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
