# Generated by Django 2.2.10 on 2020-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0002_auto_20200221_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ib_user_name',
            field=models.CharField(default='some string', max_length=20),
        ),
    ]
