# Generated by Django 2.2.10 on 2020-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0003_account_ib_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('expire_date', models.DateField()),
                ('symbols', models.TextField()),
            ],
        ),
    ]
