# Generated by Django 2.2.10 on 2020-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0004_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='long_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='security',
            name='long_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='security',
            name='short_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='security',
            name='short_min',
            field=models.IntegerField(default=0),
        ),
    ]
