# Generated by Django 2.2.10 on 2020-03-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0006_security_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='data_size',
            field=models.IntegerField(default=250),
        ),
    ]
