# Generated by Django 2.2.1 on 2020-03-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0007_security_data_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='long_max',
        ),
        migrations.RemoveField(
            model_name='security',
            name='long_min',
        ),
        migrations.RemoveField(
            model_name='security',
            name='short_max',
        ),
        migrations.RemoveField(
            model_name='security',
            name='short_min',
        ),
    ]
