# Generated by Django 2.2.1 on 2020-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0008_auto_20200311_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('security_id', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
