# Generated by Django 2.2.1 on 2020-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0009_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='security_id',
        ),
        migrations.AddField(
            model_name='journal',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
