# Generated by Django 2.2.1 on 2020-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0010_auto_20200323_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saxo_account_key',
            field=models.TextField(default=''),
        ),
    ]
