# Generated by Django 2.2.1 on 2020-04-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0011_account_saxo_account_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='symbols',
        ),
    ]
